//                                                                      -*- c++ -*-
// dsscnts.H
//
// Copyright (C) 1996 Microsoft Corp.
//      All rights reserved.
//
// counter definitions for the Data Source Service
//
// History:
//      04-10-96        alanpe          created
//


//
// DSS Object
//

#define OBJECT_DSS                                      0

#define COUNTER_DSS_CURRENT_CONNECTIONS                 2
#define COUNTER_DSS_THREADS                             4
#define COUNTER_DSS_ACTIVE_THREADS                      6
#define COUNTER_DSS_QUERIES                             8
#define COUNTER_DSS_QUERIES_PER_SEC                     10
#define COUNTER_DSS_FAILED_QUERIES                      12
#define COUNTER_DSS_FAILED_QUERIES_PER_SEC              14
#define COUNTER_DSS_RESULTS                             16
#define COUNTER_DSS_RESULTS_PER_SEC                     18
#define COUNTER_DSS_SUCCESS_QUERIES                     20
#define COUNTER_DSS_SUCCESS_QUERIES_PER_SEC             22


//
// DataSource object
//

#define OBJECT_DATASOURCE                               24

#define COUNTER_DATASOURCE_QUERIES                      26
#define COUNTER_DATASOURCE_QUERIES_PER_SEC              28
#define COUNTER_DATASOURCE_FAILED_QUERIES               30
#define COUNTER_DATASOURCE_FAILED_QUERIES_PER_SEC       32
#define COUNTER_DATASOURCE_RESULTS                      34
#define COUNTER_DATASOURCE_RESULTS_PER_SEC              36
#define COUNTER_DATASOURCE_SUCCESS_QUERIES              38
#define COUNTER_DATASOURCE_SUCCESS_QUERIES_PER_SEC      40

#define COUNTER_INDEXER_PERSISTENT_INDEXES              42
#define COUNTER_INDEXER_INDEX_SIZE                      44
#define COUNTER_INDEXER_NUM_UNIQUE_KEY                  46
#define COUNTER_INDEXER_NUM_DOCUMENTS                   48


