//+---------------------------------------------------------------------------
//
//  Microsoft Net Library System
//  Copyright (C) Microsoft Corporation, 1996 - 1997.
//
//  File:       nlindctr.h
//
//  Contents:   Counters for Indexer 
//
//  History:    5-22-97   srikants   Adapted from gsrvctr.h 
//
//----------------------------------------------------------------------------

#define OBJECT_INDEXER                                                  0

#define COUNTER_INDEXER_NUM_WORDLISTS                                   2  
#define COUNTER_INDEXER_PERSISTENT_INDEXES                              4  
#define COUNTER_INDEXER_INDEX_SIZE                                      6  
#define COUNTER_INDEXER_FILES_TO_BE_FILTERED                            8  
#define COUNTER_INDEXER_NUM_UNIQUE_KEY                                  10 
#define COUNTER_INDEXER_MERGE_PROGRESS                                  12 
#define COUNTER_INDEXER_DOCUMENTS_FILTERED                              14 
#define COUNTER_INDEXER_NUM_DOCUMENTS                                   16
#define COUNTER_INDEXER_NUM_TRANS_TO_COMPLETE                           18 
#define COUNTER_INDEXER_NUM_TRANS_IN_CI                                 20 
#define COUNTER_INDEXER_BUILD_IN_PROGRESS                               22
#define COUNTER_INDEXER_NUM_PROPS_IN_PROGRESS                           24
#define COUNTER_INDEXER_FREE1                                           26 
#define COUNTER_INDEXER_FREE2                                           28 
#define COUNTER_INDEXER_FREE3                                           30 
#define COUNTER_INDEXER_FREE4                                           32 
#define COUNTER_INDEXER_FREE5                                           34 
#define COUNTER_INDEXER_FREE6                                           36 
#define COUNTER_INDEXER_FREE7                                           38 
#define COUNTER_INDEXER_FREE8                                           40 
#define COUNTER_INDEXER_FREE9                                           42 
#define COUNTER_INDEXER_FREE10                                          44 
#define COUNTER_INDEXER_FREE11                                          46

